-- Week 1 Day 2
-- Create the gym member table.

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  email text,
  gender text check (gender in ('male', 'female', 'other')),
  date_of_birth date,
  address text,
  emergency_contact text,
  joined_at date not null default current_date,
  status text not null default 'active'
    check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_full_name_idx
  on public.members (full_name);

create index if not exists members_status_idx
  on public.members (status);

comment on table public.members is 'Gym member records used by the Member Management module.';
